### ISSUE TITLE
Transfer items.

### ISSUE THREAD

**Issue by Terryammon** [VonDoogles/TLD-QualityOfLife#1]
Hello, since the last update of TLD, I haven't been able to transfer items that are stacked (when you have to select a amount) with the QOL mod installed , i've also rolled back to the 1.6 version of the QOL mod and the bug is still present, guessing they have changed something in the game files :-(

**Comment by VonDoogles** [comment]
Unfortunately the latest update has broken even the base game without mods.  So I'm waiting until they fix those issues before I update the mod.

**Comment by Terryammon** [comment]
Coolio :-) Thanks for the reply.

**Comment by VonDoogles** [comment]
Fixed in v1.8.0.
