### ISSUE TITLE
Auto pickup with stones.

### ISSUE THREAD

**Issue by Oredan** [VonDoogles/TLD-QualityOfLife#3]
I ran into an issue on the latest version where using auto pickup on stones caused a glitched stone in my hand that wouldn't throw and was also unable to interact with anything.

**Comment by VonDoogles** [comment]
Fixed in v1.16.0.

**Comment by Oredan** [comment]
I also noticed that items weren't stacking correctly. It showed items as one stacks with auto pickup. Figured I would mention it since I noticed the update for the base game rolled out.
